from pydantic import BaseModel, Field

class ResponseFormat(BaseModel):
    punny_response: str = Field(description="A playful weather message generated by the model")
    weather_conditions: str | None = Field(default=None, description="Optional field for conditions like sunny, cloudy, etc.")

