[project]
name = "fastapidemo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13.9"
dependencies = [
    "fastapi>=0.128.0",
    "httpx>=0.28.1",
    "langchain>=1.2.3",
    "langchain-google-genai>=4.1.3",
    "langchain-mcp-adapters>=0.2.1",
    "langchain-nvidia-ai-endpoints>=1.0.1",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.40.0",
]

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
llm-test = "core.llm.client:_run"
weather-agent-test = "agents.weather_agent:_run"
fastapi = "server.main:main"
